set(_AMENT_PACKAGE_NAME "arm6")
set(arm6_VERSION "0.0.0")
set(arm6_MAINTAINER "Dr.-Ing. Denis Štogl <denis.stogl@stoglrobotics.de>, Bence Magyar <bence.magyar.robotics@gmail.com>, Christoph Froehlich <christoph.froehlich@ait.ac.at>, Sai Kishor Kothakota <sai.kishor@pal-robotics.com>")
set(arm6_BUILD_DEPENDS "ros2_control_cmake" "backward_ros" "control_msgs" "controller_interface" "hardware_interface" "kdl_parser" "pluginlib" "rclcpp_lifecycle" "rclcpp" "realtime_tools" "trajectory_msgs")
set(arm6_BUILDTOOL_DEPENDS "ament_cmake")
set(arm6_BUILD_EXPORT_DEPENDS "backward_ros" "control_msgs" "controller_interface" "hardware_interface" "kdl_parser" "pluginlib" "rclcpp_lifecycle" "rclcpp" "realtime_tools" "trajectory_msgs")
set(arm6_BUILDTOOL_EXPORT_DEPENDS )
set(arm6_EXEC_DEPENDS "controller_manager" "gazebo_ros" "joint_state_broadcaster" "joint_state_publisher_gui" "launch_ros" "launch" "robot_state_publisher" "ros2_control_demo_description" "ros2controlcli" "ros2launch" "rviz2" "urdf" "xacro" "backward_ros" "control_msgs" "controller_interface" "hardware_interface" "kdl_parser" "pluginlib" "rclcpp_lifecycle" "rclcpp" "realtime_tools" "trajectory_msgs")
set(arm6_TEST_DEPENDS "ament_cmake_pytest" "launch_testing" "launch" "liburdfdom-tools" "rclpy")
set(arm6_GROUP_DEPENDS )
set(arm6_MEMBER_OF_GROUPS )
set(arm6_DEPRECATED "")
set(arm6_EXPORT_TAGS)
list(APPEND arm6_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
